name: Run My Name Bash Script

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Execute my_echo.sh
        run: bash my_echo.sh
